### ISSUE TITLE
[PE-D][Tester B] Edit Command: Groups

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-1/tp#101]
Perhaps mentioning certain command parameters must be given in groups would be beneficial to your UG. e.g. from and to

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: B-enguin/ped#10

**Comment by PohSayKeong** [comment]
This will come under editft feature, reassigning to Zhong Yi
