### ISSUE TITLE
[PE-D][Tester C] Unexplained technical term

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-1/tp#105]
Initial reading of the UG, term `default course` confused, and using the `course c/CS2100` command and saw no field show confused me initially. Got it after playing around with the application though.

It was not a major issue, but it would be nice if there is a table/index for words that might not be very common / specific to your Target Audience.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: LicongHuang/ped#5

**Comment by PohSayKeong** [comment]
Resolved in #123
