### ISSUE TITLE
[PE-D][Tester B] List Command: UG has traces of merge conflict

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T10-1/tp#109]
![image.png](https://raw.githubusercontent.com/B-enguin/ped/main/files/7d643059-5e54-4160-bc66-5f4e7980850e.png)

Perhaps this was missed out in your UG

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: B-enguin/ped#12

**Comment by lshaoqin** [comment]
Duplicate issue to #113
