### ISSUE TITLE
[PE-D][Tester D] Changing the dayOfWeek property of a lesson in an entry in addressbook.json to an invalid day does not raise any errors

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-1/tp#116]
![Screenshot 2023-11-03 at 5.10.56 PM.png](https://raw.githubusercontent.com/PetrichorPrecipice/ped/main/files/a526e2dc-4918-4f79-b156-412cdbbde871.png)

Setting dayOfWeek to SATURDAY in addressbook.json, a day that cannot be set in the application itself, does not raise any errors when starting the program again. This is problematic if an error such as this one is not detected by the application which can lead to further errors down the road.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: PetrichorPrecipice/ped#8

**Comment by PohSayKeong** [comment]
According to our UG, this would cause the addressbook to be cleared
